### ISSUE TITLE
[TRACKER] Font rendering issues

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#156]
This is to be the tracker issue for font rendering related issues. Let's hope we can tackle them :muscle: 

- [x] sometimes font sizes are displayed in unreadable rectangle boxes. (reason: FT_PIXEL_MODE_MONO is treated as if it would be FT_PIXEL_MODE_GRAY)
- [x] sometimes it looks like the cell height is too high (visible gab between glyphs that should not be there)?
- [x] some glyph dispositions: because some glyphs are selected from a font (fallback) that is not monospace, leading to awkward visual behavior

# glyph disposition along x axis

expected output:
![image](https://user-images.githubusercontent.com/56763/106069159-46c3d480-6102-11eb-8f45-2fddec0d5a38.png)

actual output: 
![image](https://user-images.githubusercontent.com/56763/106069298-8c809d00-6102-11eb-962f-dc243124bed8.png)

test script:
```sh
echo -ne "\e[41m \e[42m \e[43m \e[m\n" 
echo -ne "\e[42m \e[43m\u256d\e[41m\n"
echo -ne "\e[43m \e[41m\u2570\e[42m\n"
echo -ne "\e[41m \e[42m \e[43m \e[m\n"
```

**Comment by uspasojevic96** [comment]
10.14.6 (Mojave) font rendering issues

Had to change .yml to .txt cuz github

[output.log](https://github.com/christianparpart/contour/files/5781766/output.log)
![Screen Shot 2021-01-07 at 2 18 19 PM](https://user-images.githubusercontent.com/3018800/103897029-361bd200-50f3-11eb-9552-497439245c78.png)
[contour.txt](https://github.com/christianparpart/contour/files/5781775/contour.txt)

**Comment by christianparpart** [comment]
> 10.14.6 (Mojave) font rendering issues

that bug i could finally reproduce. it suddenly happened. The reason is, that for text (non-emoji/colored glyphs) I expect the bitmap to be 256 bit anti aliased alpha map. I did not check for the resulting bitmap format of the freetype render call, which sometimes (on some sizes) returns FT_PIXEL_MODE_MONO (which means AA disabled binary pixelated glyphs).

**Comment by ResuBaka** [comment]
There looks like a new issue with the render mode that some types of icons do not get rendered correctly or that least the one where I can see an issue.

Commit: f9cce2f25d02b625ca2f021f5582019c69eb258e
Branch: master

Render Mode:

### light
![image](https://user-images.githubusercontent.com/15260832/104839894-7aae2700-58c4-11eb-8ad9-c6010d1b0077.png)

### gray
![image](https://user-images.githubusercontent.com/15260832/104839930-b21cd380-58c4-11eb-8b57-6e2421c2bd10.png)

### monochrome
![image](https://user-images.githubusercontent.com/15260832/104839962-d4aeec80-58c4-11eb-876b-4fad641c99c8.png)

### lcd
![image](https://user-images.githubusercontent.com/15260832/104839975-e85a5300-58c4-11eb-917c-c7e8f6a8becd.png)


Version: 0.1.0-prerelease-106
![image](https://user-images.githubusercontent.com/15260832/104840011-1049b680-58c5-11eb-84d7-e1ece8cfa980.png)

**Comment by christianparpart** [comment]
@ResuBaka thanks

**Comment by christianparpart** [comment]
> There looks like a new issue with the render mode that some types of icons

Fixes (also merged to master).

**Comment by christianparpart** [comment]
@uspasojevic96 I think I have sufficiently addressed all font related issues that have been mentioned above. At least I could reproduce them and now that is fixed. I'd love to see if that is working for you on the machine you created these screenshots with, too?

**Comment by christianparpart** [comment]
Forgot to mention, it's in `wip` branch.

```sh
git fetch
git co wip
git reset --hard origin/wip
```

**Comment by christianparpart** [comment]
I'd like not to close this ticket just yet (I am not too happy about font fallback when comparing to other terminal emulators), but with regards to all the 3 above mentioned issues, are they fixed for you now, too?

**Comment by whisperity** [comment]
#167 Really went sideways to the font discussion as opposed to its purpose, so what can I post here to detail? The glpyhs , , , and  all seem to come from `FontAwesome` which is installed system-wide on my machine. Normally, I have my font set to `JetBrains Mono` in both Konsole and Contour configuration.

**Comment by christianparpart** [comment]
The takeaway is that in your case font fallback is not working or at least not considering FontAwsome. I am currently reworking font handling, amongst other related topics).

**Comment by christianparpart** [comment]
I think we can close this finally. Any new thing can be put into its own ticket, I think.
