### ISSUE TITLE
aeroterm: Cursor Support

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#53]
### TODO
* [x] mode: hide/show cursor
* [x] shape: Block
* [x] shape: Rectangle
* [x] shape: Underline
* [x] shape: Bar
* [x] support custom cursor colors (as part of ColorPalette) 
* [x] configuration setting & runtime reloading
* [x] mode: blinking ~~(also switchable via CSI sequence)~~
